language: php
sudo: false
services:
  - mysql
  - postgresql

php:
  - 7.2

env:
  global:
    - OC_PASS=ampache

matrix:
  include:
    # ownCloud versions
    - env: DB=mysql CLOUD=owncloud CORE_BRANCH=stable10
    - env: DB=mysql CLOUD=owncloud CORE_BRANCH=master

    # Nextcloud versions
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable13
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable14
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable15
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable16
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable17
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable18
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable19
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable20
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable21
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=master

    # PostgreSQL
    - env: DB=pgsql CLOUD=nextcloud CORE_BRANCH=stable15

    # PHP versions
    - php: 7.1
      env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable15
    - php: 7.3
      env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable15
    - php: 7.4
      env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable18
    - php: 8.0
      env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable21
  allow_failures:
    - env: DB=mysql CLOUD=owncloud CORE_BRANCH=stable10
    - env: DB=mysql CLOUD=owncloud CORE_BRANCH=master
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=stable21
    - env: DB=mysql CLOUD=nextcloud CORE_BRANCH=master
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - "/tmp/downloadedData"

before_install:
  - php --info
  # Set up DB
  - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s oc_autotest; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE oc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "GRANT ALL ON oc_autotest.* TO 'oc_autotest'@'localhost';"; fi

  - composer self-update
  - composer install
  - cd ..
  - sh -c "if [ '$CLOUD' = 'nextcloud' ]; then git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core; fi;"
  - sh -c "if [ '$CLOUD' = 'owncloud' ]; then git clone https://github.com/owncloud/core.git --recursive --depth 1 -b $CORE_BRANCH core; fi;"
  - cd core
  - git submodule update --init
  - mkdir data
  # On ownCloud 10.x, we need to run 'make'. Furthermore, the Makefile is not totally compatible
  # with our Travis environment and has to be patched slightly.
  - sh -c "if [ '$CLOUD' = 'owncloud' ] && [ $CORE_BRANCH = 'stable10' -o $CORE_BRANCH = 'master' ]; then sed -i 's/php \$(COMPOSER_BIN)/\$(COMPOSER_BIN)/g' Makefile; make; fi;"
  - cd ..
  - mv music core/apps/

before_script:
  # setup ownCloud
  - php -f core/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
  - php -f core/occ app:enable music
  - php -f core/occ user:add ampache --password-from-env
  # download test data (only if not cached already)
  - core/apps/music/tests/downloadTestData.sh ${TRAVIS_BUILD_DIR}/../core/data/ampache
  - php -f core/occ files:scan ampache
  - php -f core/occ music:scan ampache
  # add Ampache API key with ampache as password for user ampache
  - bash -c "if [ '$DB' == 'sqlite' ]; then sqlite3 data/owncloud.db 'INSERT INTO oc_music_ampache_users (user_id, hash) VALUES (\"ampache\", \"3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18\");'; fi"
  - bash -c "if [ '$DB' == 'mysql' ]; then mysql -u oc_autotest oc_autotest -e 'INSERT INTO oc_music_ampache_users (user_id, hash) VALUES (\"ampache\", \"3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18\");'; fi"
  - bash -c "if [ '$DB' == 'pgsql' ]; then psql -U oc_autotest -d oc_autotest -w -c \"INSERT INTO oc_music_ampache_users (user_id, hash) VALUES ('ampache', '3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18');\"; fi"
  - cd core
  - php -S localhost:8888 -t . &
  - cd apps/music
  - cp tests/behat.yml.travis tests/behat.yml

script:
  - vendor/bin/phpunit --coverage-clover clover-unit.xml --configuration tests/php/unit/phpunit.xml tests/php/unit
  - vendor/bin/phpunit --coverage-clover clover-integration.xml --configuration tests/php/integration/phpunit.xml tests/php/integration
  - cd tests && ../vendor/bin/behat

  # Post coverage report from NC13 to Scrutinizer as this version is included only in a single configuration, and run early in the queue
  - bash -c "if [ '$CORE_BRANCH' == 'stable13' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - bash -c "if [ '$CORE_BRANCH' == 'stable13' ]; then php ocular.phar code-coverage:upload --format=php-clover ../clover-unit.xml; fi"
  - bash -c "if [ '$CORE_BRANCH' == 'stable13' ]; then php ocular.phar code-coverage:upload --format=php-clover ../clover-integration.xml; fi"

  # debug section to check what went wrong
  - cat ../../../data/${CLOUD}.log

